apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: il2-core-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://gitlab.com/your-org/your-repo.git"
    targetRevision: main
    path: "kustomize/overlays/il2/core-services"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "core-services"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
